const cities = [
  'Islamabad',
  'Karachi',
  'Karachi ',
  'Karachi',
  'Quetta',
  'Rawalpindi',
  'Rawalpindi',
  'Karachi ',
  'Karachi ',
  'North waziristan',
  'Kohat',
  'Attock ',
  'Sialkot',
  'Lahore ',
  'Quetta',
  'Swat',
  'Islamabad',
  'Karachi ',
  'Hangu',
  'Karachi',
  'Karachi ',
  'Bannu',
  'North Waziristan',
  'Lasbela',
  'Malakand ',
  'Peshawar',
  'Bannu',
  'North Waziristan',
  'Islamabad',
  'Peshawar ',
  'D.I Khan ',
  'Lakki Marwat',
  'Tank',
  'Islamabad ',
  'Quetta ',
  'Gujrat',
  'Charsadda',
  'Peshawar ',
  'Tank ',
  'North Waziristan',
  'Swat ',
  'North Waziristan',
  'North Waziristan',
  'D.I Khan',
  'Swat ',
  'Islamabad ',
  'North Waziristan',
  'Lasbela',
  'Hangu',
  'Kohat ',
  'North Waziristan',
  'Islamabad ',
  'Swat ',
  'Kuram Agency ',
  'Tank',
  'North Waziristan',
  'Bannu',
  'Hangu',
  'North Waziristan',
  'Shangla ',
  'Bajaur Agency',
  'South Waziristan',
  'Rawalpindi',
  'Rawalpindi',
  'D.I Khan',
  'Haripur',
  'Tank',
  'bannu',
  'karachi ',
  'Swat',
  'Rawalpindi',
  'Sargodha',
  'Peshawar',
  'Rawalpindi',
  'Rawalpindi',
  'Peshawar',
  'Swat',
  'Attock ',
  'Quetta ',
  'Nowshehra',
  'Kohat',
  'Charsadda ',
  'Swat',
  'Rawalpindi',
  'Swat',
  'Lahore ',
  'Mohmand agency',
  'Peshawar',
  'North Waziristan',
  'Rawalpindi',
  'Quetta ',
  'Charsadda ',
  'North Waziristan',
  'Swat',
  'Kuram Agency ',
  'Rawalpindi',
  'Swat',
  'Bajaur Agency',
  'Dara Adam Khel',
  'Lahore ',
  'Lahore ',
  'Lahore ',
  'Swat',
  'South Waziristan',
  'Khyber Agency',
  'Bannu',
  'Swat',
  'Mardan',
  'Islamabad',
  'Islamabad',
  'D.I Khan',
  'Lahore ',
  'D.I Khan',
  'Rawalpindi',
  'Swat',
  'Kohat',
  'Peshawar',
  'Swat',
  'North waziristan',
  'Islamabad',
  'Swat',
  'Quetta',
  'Peshawar',
  'Bhakkar ',
  'Islamabad',
  'Khyber Agency',
  'Orakzai Agency',
  'Swat',
  'Mohmand Agency',
  'Bannu',
  'Mardan',
  'South Waziristan',
  'Hangu',
  'Swat',
  'Bajaur Agency',
  'Peshawar',
  'Charsadda',
  'Swat',
  'Bajaur Agency',
  'Buner',
  'Swat',
  'Charsadda',
  'Orakzai Agency',
  'Buner',
  'Buner',
  'D.I Khan',
  'Bannu',
  'Swat',
  'D.G Khan ',
  'Swat',
  'Khyber Agency',
  'Bannu',
  'D.I Khan ',
  'Bannu',
  'Bannu',
  'Pishin',
  'Peshawar',
  'Rawalpindi',
  'Islamabad',
  'Tank',
  'Khyber Agency',
  'North waziristan',
  'Islamabad',
  'North waziristan',
  'Chakwal ',
  'Charsadda',
  'Hangu',
  'Peshawar',
  'Dara Adam Khel',
  'Tank',
  'Lahore',
  'Peshawar',
  'D.I Khan ',
  'Upper Dir',
  'Islamabad',
  'Peshawar',
  'Peshawar',
  'Lahore',
  'Nowshehra',
  'Swat',
  'Muzaffarabad',
  'Khyber Agency',
  'Peshawar',
  'Rawalpindi',
  'Peshawar',
  'North Waziristan',
  'South Waziristan',
  'Swat',
  'swat',
  'North Waziristan',
  'Kohat',
  'Swat ',
  'Peshawar',
  'Khyber Agency',
  'Swat',
  'Hangu',
  'Malakand ',
  'Kohat',
  'Dara Adam Khel',
  'Totalai',
  'Bannu',
  'Peshawar',
  'bannu',
  'Islamabad',
  'Peshawar',
  'Shangla ',
  'Kohat',
  'Lahore',
  'Peshawar',
  'Islamabad',
  'Attock ',
  'Chakwal ',
  'Rawalpindi',
  'Lahore',
  'Peshawar',
  'Peshawar',
  'Charsadda',
  'Peshawar',
  'Bannu',
  'Peshawar',
  'Peshawar',
  'Peshawar',
  'Swat',
  'Islamabad',
  'Rawalpindi',
  'Peshawar',
  'Lahore',
  'Multan',
  'D.G Khan',
  'Bannu',
  'Lower Dir',
  'Peshawar',
  'Peshawar',
  'Islamabad',
  'Muzaffarabad',
  'Lakki marwat',
  'Sudhanoti',
  'Khyber Agency ',
  'peshawar',
  'Poonch',
  'Tank',
  'Bajaur Agency',
  'Khyber Agency',
  'Bannu',
  'Khyber Agency',
  'Mansehra',
  'Swat',
  'Karak',
  'Hangu',
  'Lahore ',
  'Lahore ',
  'Swat',
  'Tank',
  'Bajaur Agency',
  'Peshawar',
  'Lower Dir',
  'Quetta',
  'Kohat',
  'Kohat',
  'Peshawar',
  'Peshawar',
  'Swat',
  'Bajaur Agency',
  'Lahore ',
  'Lahore ',
  'Mohmand Agency ',
  'Kohat',
  'Sargodha',
  'Nowshehra',
  'Peshawar',
  'South waziristan',
  'Lahore ',
  'Quetta',
  'Mardan',
  'lakki marwat',
  'Quetta',
  'Karachi',
  'Lakki marwat',
  'Swabi ',
  'Dara Adam khel',
  'Karachi ',
  'Poonch',
  'South waziristan',
  'Bannu',
  'Mohmand Agency ',
  'Quetta',
  'Kohat',
  'Hangu',
  'Islamabad',
  'Peshawar',
  'Bajaur Agency',
  'Muzaffarabad',
  'Bannu',
  'Lahore',
  'Bajaur Agency',
  'Peshawar',
  'Mardan',
  'Mohmand Agency ',
  'Malakand ',
  'Bannu',
  'Karachi',
  'Hangu',
  'Peshawar',
  'Hangu',
  'Swabi ',
  'Charsadda',
  'Dara Adam khel',
  'D.G Khan ',
  'Lower Dir',
  'Quetta',
  'Bajaur Agency',
  'Charsadda',
  'D.G Khan ',
  'Peshawar',
  'Hangu',
  'Bajaur Agency',
  'Nowshehra',
  'Peshawar',
  'Islamabad',
  'D.I Khan ',
  'Peshawar',
  'South waziristan',
  'South waziristan',
  'Mohmand Agency ',
  'Peshawar',
  'Khyber Agency',
  'Quetta',
  'Lakki marwat',
  'Quetta',
  'Lower Dir',
  'karachi',
  'Nowshehra',
  'Swabi ',
  'Karachi',
  'Karachi',
  'Bannu',
  'Gujrat',
  'Peshawar',
  'Khyber Agency',
  'D.I Khan',
  'Peshawar',
  'Kuram Agency ',
  'Upper Dir',
  'Peshawar',
  'Peshawar',
  'D.I Khan',
  'Peshawar',
  'Peshawar',
  'Khyber Agency',
  'Karachi',
  'Bajaur Agency',
  'Peshawar',
  'Quetta',
  'Bannu',
  'Peshawar',
  'Kuram Agency ',
  'Dara Adam khel',
  'Buner',
  'Peshawar',
  'Karachi',
  'Mohmand Agency ',
  'Karachi',
  'Rawalpindi',
  'D.I Khan',
  'South Waziristan',
  'Peshawar',
  'South waziristan',
  'Peshawar',
  'Quetta',
  'Hangu',
  'Hangu',
  'Bannu',
  'Quetta',
  'Peshawar',
  'Peshawar',
  'North waziristan',
  'Peshawar',
  'Peshawar',
  'North waziristan',
  'Bajaur Agency',
  'Quetta',
  'Peshawar',
  'Shikarpur',
  'Hangu',
  'Bannu',
  'Karachi',
  'Quetta',
  'Peshawar',
  'North waziristan',
  'Quetta',
  'Quetta',
  'Mardan',
  'Peshawar',
  'Quetta',
  'Hangu',
  'Sukkur',
  'Kuram Agency ',
  'Quetta',
  'Peshawar',
  'Chaman',
  'Hangu',
  'South waziristan',
  'D. I Khan',
  'Bannu',
  'North waziristan',
  'Khyber Agency',
  'Rawalpindi',
  'North waziristan',
  'Karachi',
  'Quetta',
  'Hangu',
  'Karachi',
  'Rawalpindi',
  'Peshawar',
  'Karachi',
  'Peshawar',
  'Khanewal',
  'Peshawar',
  'Karachi',
  'Peshawar',
  'Islamabad',
  'Peshawar',
  'Karachi',
  'Peshawar',
  'Fateh Jang',
  'Taftan',
  'Karachi',
  'Peshawar',
  'North waziristan',
  'Peshawar',
  'Quetta',
  'Tirah Valley',
  'Quetta',
  'Wagah',
  'Peshawar',
  'Zhob',
  'Shikarpur',
  'Peshawar',
  'Lahore',
  'Rawalpindi',
  'Lahore',
  'Karachi',
  'KURRAM AGENCY',
  'Karachi',
  'Karachi',
  'Lahore',
  'Sargodha',
  'North waziristan',
  'Peshawar',
  'Lahore',
  'Quetta',
  'ATTOCK',
  'MULTAN',
  'Khyber Agency',
  'Karachi',
  'Taunsa',
  'Quetta',
  'Jacobabad',
  'Mardan',
  'Quetta',
  'Peshawar',
  'Zhob',
  'Quetta',
  'Shabqadar-Charsadda',
  'Lahore',
  'Khyber Agency',
  'Mardan',
  'Mardan',
  'Quetta',
  'Mardan',
  'Shikarpur',
  'Mohmand Agency ',
  'Quetta',
  'Khuzdar',
  'Mohmand Agency',
  'Bannu',
  'Lahore',
  'Ghallanai, Mohmand Agency ',
  'Hayatabad',
  'Mosal Kor, Mohmand Agency',
  'Sehwan town',
  'Tangi, Charsadda District',
  'Lahore',
  'Quetta',
  'Kohat',
  'Quetta',
  'Chaman',
  'Peshawar',
  'Peshawar',
  'Lahore',
  'Quetta',
  'Quetta',
  'Quetta',
  'Quetta',
  'Peshawar',
  'Quetta',
];
